<?php

namespace AppBundle\Repository;

/**
 * AvesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName($characters) {

        $query = $this->createQueryBuilder('a');
        $query
            ->where('a.nameVern LIKE :characters')
            ->setParameter('characters', "$characters%")
            ->orWhere('a.tlName LIKe :characters')
            ->setParameter('characters', "$characters%")
            ->orderBy('a.id')
            ->setMaxResults(20);
        return $query->getQuery()->getResult();
    }

    public function findById($id) {

        $query = $this->createQueryBuilder('a');
        $query
            ->where('a.id=:id')
            ->setParameter('id', $id);
        return $query->getQuery()->getResult();
    }
}
