<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllUnreadComments() {
        $qb = $this->createQueryBuilder('comment');
        $qb
            ->where('comment.readed=:unread')
            ->setParameter('unread', false)
            ->orderBy('comment.commentDate', 'DESC');
        return $qb->getQuery()->getResult();
    }
}
