<?php

namespace AppBundle\Repository;
use Symfony\Component\HttpFoundation\Request;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNbNews()
    {
        $nbNews = $this->createQueryBuilder('n');
        $nbNews
            ->select('COUNT(n)')
            ->where('n.published = 1');
        return $nbNews->getQuery()->getOneOrNullResult();
    }

    public function find6News($curentPage)
    {
        $start = ($curentPage - 1)*6;
        $listNews = $this->createQueryBuilder('n');
        $listNews
            ->where('n.published = 1')
            ->orderBy('n.newsDate', 'DESC')
            ->setFirstResult($start)
            ->setMaxResults(6);
        return $listNews->getQuery()->getResult();
    }

    public function findByNewsDate($today){
        $listNews =$this->createQueryBuilder('n');
        $listNews
            ->where('n.newsDate <= :today')
            ->andwhere('n.published = 1')
            ->setParameter('today', $today)
            ->orderBy('n.newsDate', 'DESC')
            ->setMaxResults(3);
        return $listNews->getQuery()->getResult();
    }

    public function findByNewsId($Id){
        $article =$this->createQueryBuilder('n');
        $article
            ->where('n.id = :id')
            ->setParameter('id', $Id);
        return $article->getQuery()->getResult();
    }
}
