<?php

namespace AppBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAvesId($id){
        $queryBuilder =$this->createQueryBuilder('o');
        $queryBuilder
            ->where('o.aves=:id')
            ->setParameter('id', $id);
        return $queryBuilder->getQuery()->getResult();
    }

    public function findByObsDate($today){
        $listObs =$this->createQueryBuilder('obs');
        $listObs
            ->where('obs.observationDate < :today')
            ->andWhere('obs.isValid = 1')
            ->setParameter('today', $today)
            ->orderBy('obs.id', 'DESC')
            ->setMaxResults(3);
        return $listObs->getQuery()->getResult();
    }


    public function findAllObservationsNotValidate() {
        $qb = $this->createQueryBuilder('ob');
        $qb
            ->where('ob.isValid=:validate')
            ->setParameter('validate', false)
            ->orderBy('ob.observationDate', 'DESC');
        return $qb->getQuery()->getResult();
    }

}
