
app:
    resource:          '@AppBundle/Controller/'
    type:              annotation

hwi_oauth_redirect:
    resource:          "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:            /connect

hwi_oauth_connect:
    resource:          "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:            /connect

hwi_oauth_login:
    resource:          "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:            /connect

facebook_login:
    path:              /connect/check-facebook

google_login:
    path:              /connect/check-google

twitter_login:
    path:              /connect/check-twitter

fos_user:
    resource:          "@FOSUserBundle/Resources/config/routing/all.xml"

association:
      path: /association/
      defaults:
          _controller: AppBundle:Core:association

landing:
      path: /landing/
      defaults:
          _controller: AppBundle:Core:landing

news:
      path: /news/{page}
      defaults:
          _controller: AppBundle:Core:news

contact:
      path: /contact/
      defaults:
          _controller: AppBundle:Core:contact

article:
      path: /article/{id}
      defaults:
          _controller: AppBundle:Core:article

