security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:

        ROLE_PARTICULAR:                    [ROLE_USER]
        ROLE_NATURALIST:                    [ROLE_PARTICULAR]
        ROLE_ADMIN:                         [ROLE_NATURALIST]

    providers:
        fos_userbundle:
            id:                             fos_user.user_provider.username_email


    firewalls:
        dev:
            pattern:                        ^/(_(profiler|wdt)|css|images|js)/
            security:                       false

        main:
            pattern:                        ^/
            form_login:
                provider:                   fos_userbundle
                default_target_path:        fos_user_profile_edit   # redirect to the profil edit page
                failure_path:               fos_user_security_login  # redirect to the login page in case of failure
                csrf_token_generator:       security.csrf.token_manager
                success_handler:            app.redirect.after.login
            remember_me:
              secret:                       '%secret%'
            logout:                         true
            anonymous:                      true

            oauth:
                # Declare the OAuth Callback URLs for every resource owner
                resource_owners:
                    facebook:               "/connect/check-facebook"
                    google:                 "/connect/check-google"
                    twitter:                "/connect/check-twitter"
                # Provide the original login path
                login_path:                 /login
                failure_path:               /login
                # Inject a service fos_user.oauth_provider
                oauth_user_provider:
                    service: app.fos_user.oauth_provider

    access_control:
        - { path: ^/connect, roles:               IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role:                 IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role:               IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role:              IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/add_observation, role:        ROLE_USER }
        - { path: ^/observation/validate, role:   ROLE_NATURALIST }
        - { path: ^/observation/edit, role:       ROLE_NATURALIST }
        - { path: ^/observation/remove, role:     ROLE_NATURALIST }
        - { path: "/{YOUR-PREFIX}/profile/confirm-email-update/{token}", roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/admin, role:                  ROLE_ADMIN }
